# Site settings
title: Ziyi Zhou's Blog
SEOTitle: 周孜奕的博客 | Ziyi Zhou's Blog
header-img: img/bg/home.jpg
email: Ziyi_zhou@foxmail.com
description: ""
keyword: ""
url: "https://ZiyiZhou.github.io"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'


# SNS settings
RSS: false
#weibo_username:    2517170031 # llArcherll
#linkedin_username: wenlong-shen-2247a333
#twitter_username:  
#facebook_username:  
zhihu_username:     di-xi-pan-24
github_username:    Konymous
#dockerhub_username:  wenlongshen
#kaggle_username:  shenwenlong
#researchgate_username: Wenlong_Shen2


# Build settings
highlighter: rouge
permalink: pretty
paginate: 7
exclude: ["README.md"]
anchorjs: false       # if you want to customize anchor. check out line:181 of `post.html`


# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


# Analytics settings
# Baidu Analytics 
ba_track_id: e33e0e176e2b34f2cacb3c1c38cfde29

# Google Analytics
ga_track_id: 'UA-33382825-4'            # Format: UA-xxxxxx-xx


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "修身、齐家、治国、平天下"
sidebar-avatar: /img/avatar.jpg


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 7              # A tag will be featured if the size of it is more than this condition value


# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Contact
contact: true
email: Ziyi_zhou@foxmail.com

# Comments
comments:
  disqus: false
  disqus_username: https-ZiyiZhou-github-io

  gitalk: false
  gitalk_clientID: '6efc0e62a79258590bc8'
  gitalk_Secret: '39ed240369e743083f46f5855bf7869fe079d4d3'
  gitalk_repo: 'ZiyiZhou.github.io'
  gitalk_owner: 'ZiyiZhou'
  gitalk_admin: ['ZiyiZhou']
  distractionFreeMode: true


# Friends
friends: [
    {
        title: "wenlongshen's blog",
        href: "https://wenlongshen.github.io/"
    }, {
        title: "openbiox",
        href: "http://openbiox.org/"
    }
]
